import Head from 'next/head'
import styles from '../styles/index.module.scss'
import {BsCaretLeftFill, BsCaretRightFill} from 'react-icons/bs'
// import audio elements
// import useSound from 'use-sound'
// import mainMenuTrack from '../public/audio/tracks/Main Menu.mp3'
import { useEffect, useState } from 'react'
import Callout from '../components/Callout'
import Field from '../components/Field'
import MainMenu from '../components/MainMenu'
import Results from '../components/Results'


export default function Home() {
  // main game loop configuration
  const [playing, setPlaying] = useState(false)
  const [end, setEnd] = useState(false)
  const [clock, setClock] = useState(0)

  // track player position
  const [playerPosition, setPlayerPosition] = useState(1)
  const moveLeft = () => {
    if (playerPosition > 0) {
      setPlayerPosition(playerPosition-1)
    }
  }
  const moveRight = () => {
    if (playerPosition < 3) {
      setPlayerPosition(playerPosition+1)
    }
  }

  // const [play] = useSound(boopSfx)

  // useEffect(() => `{play()}, [])

  // state to display callout
  const [showCallout, setShowCallout] = useState(false)
  useEffect(() => {
    if (showCallout) {
      // show callout for 5s
      setTimeout(() => setShowCallout(false), 3000)
    } else {
      //randomly generate callout after 20s, keep track of callout count
      setTimeout(() => {setClock(clock+1);setShowCallout(true)}, Math.random()*10000+20000)
      // setTimeout(() => setShowCallout(true), 2000)
    }
  }, [showCallout])
  // end after X callouts
  const maxCallouts = 1
  useEffect(() => {
    if (clock >= maxCallouts) {
      setTimeout(() => {setPlaying(false); setEnd(true)}, Math.round(Math.random()*300))
    }
  }, [clock])

  return (
    <>
      <Head>
        <title>UNI-verse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {showCallout & playing ? <Callout /> : ''}
        <div className={styles.content}>
          <div className={styles.headerContainer}>
            <h1>UNI-verse</h1>
            <span>Can you beat the system?</span>
          </div>
          <div className={styles.gameContent}>
            {playing ? <Field playerPosition={playerPosition} /> : ''}
            {!playing & !end ? <MainMenu play={() => setPlaying(true)} /> : ''}
            {end ? <Results /> : ''}
          </div>
          {playing ? <div className={styles.buttonContainer}>
            <div className={`${styles.button} ${styles.leftButton}`} onClick={moveLeft}><BsCaretLeftFill /></div>
            <div className={`${styles.button} ${styles.rightButton}`} onClick={moveRight}><BsCaretRightFill /></div>
          </div> : ''}
        </div>
      </main>
    </>
  )
}
